### ISSUE TITLE
Standalone repo project from 3.0.0 archetype will not run out-of-the-box

### ISSUE THREAD

**Issue by jpotts** [Alfresco/alfresco-sdk#454]
## I'm submitting a ...   (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```
## Expected Behavior
1. Create a new project with mvn archetype:generate -Dfilter=org.alfresco:
2. Select option 4 (org.alfresco.maven.archetype:alfresco-platform-jar-archetype)
3. The project creates successfully.
4. Switch to root of the project.
5. Run `chmod u+x run.sh`
6. Run `./run.sh`

Expect the server to start up successfully.

## Current Behavior

Currently, at step 6 from above, the following error will occur:

[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3.0.0:run (default-cli) on project actions-tutorial-repo: Unable to execute mojo: Unable to find artifact. Failure to find org.alfresco:alfresco:war:5.2.e in https://artifacts.alfresco.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of alfresco-public has elapsed or updates are forced

## Possible Solution

A workaround is to edit pom.xml and change the SDK version to 3.0.0-SNAPSHOT.

## Your Environment

* Alfresco SDK version used: 3.0.0
* Alfresco version used: Default for SDK
* Output of command 'mvn -version': 

Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_77, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

**Comment by ohej** [comment]
I have not been able to reproduce this issue, however I know we recently had some issues with nexus. Can you try running with -U and see if that changes it? Otherwise please provide the full output from the terminal (and your pom if possible) and I'll have a deeper look.

**Comment by jpotts** [comment]
I tried -U and also cleared out my Maven repo of SDK-related artifacts, but
I will try again.

**Comment by douglascrp** [comment]
Ok, this is the first time I am trying SDK 3.0 for a brand new projet.
The other times, the project already existed, and I simply updated the SDK version from beta5 to 3.0.0.

When creating a new project just like Jeff described, I saw the same behavior.

**Comment by douglascrp** [comment]
I guess the problem is related with the pull request #449

**Comment by douglascrp** [comment]
After installing the 3.0.1-SNAPSHOT version locally and updating the SDK version to 3.0.1-SNAPSHOT, I was able to run the project.

**Comment by ohej** [comment]
I'm not sure the PR you provided @douglascrp will fix this issue. I've tried with a fresh VM and the artifacts resolved correctly. Will have to investigate more

**Comment by douglascrp** [comment]
@ohej Well, it did solve the problem for me.

**Comment by douglascrp** [comment]
@jpotts As a quick test, can you please try adding the following property inside the pom.xml file?

```
<alfresco.platform.war.artifactId>alfresco-platform</alfresco.platform.war.artifactId>
```

**Comment by jpotts** [comment]
I noticed that some of my standalone repo projects using SDK 3.0.0 no longer have this problem, so I tested with an out-of-the-box project this morning and this behavior is no longer exhibited. Unfortunately, I've made multiple upgrades since the original problem (to Maven 3.5 and to Mac OS 10.12.5) to I am not sure what fixed it.

**Comment by wkamdem** [comment]
following this tutorial http://ecmarchitect.com/alfresco-developer-series-tutorials/maven-sdk/tutorial/tutorial.html of jpotts. i have the following problem runing the run.bat file. 

[ERROR] Failed to execute goal org.alfresco.maven.plugin:alfresco-maven-plugin:3
.0.0:run (default-cli) on project someco-mvn-tutorial-repo: Unable to execute mo
jo: java.lang.reflect.InvocationTargetException: Invalid plugin descriptor for o
rg.apache.tomcat.maven:tomcat7-maven-plugin:2.2 (C:\Users\wt\.m2\repository\org\
apache\tomcat\maven\tomcat7-maven-plugin\2.2\tomcat7-maven-plugin-2.2.jar), Plug
in's descriptor contains the wrong group ID: org.apache.axis2, Plugin's descript
or contains the wrong artifact ID: axis2-ant-plugin, Plugin's descriptor contain
s the wrong version: 1.4 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
java.lang.NoClassDefFoundError: de/schlichtherle/truezip/fs/FsLockController$1Sy
nc
        at de.schlichtherle.truezip.fs.FsLockController.sync(FsLockController.ja
va:240)
        at de.schlichtherle.truezip.fs.archive.zip.KeyController.sync(KeyControl
ler.java:128)
        at de.schlichtherle.truezip.fs.FsDecoratingController.sync(FsDecoratingC
ontroller.java:131)
        at de.schlichtherle.truezip.fs.FsFalsePositiveArchiveController.sync(FsF
alsePositiveArchiveController.java:480)
        at de.schlichtherle.truezip.fs.FsManager.sync(FsManager.java:105)
        at de.schlichtherle.truezip.fs.FsDefaultManager.sync(FsDefaultManager.ja
va:190)
        at de.schlichtherle.truezip.fs.FsSyncShutdownHook$Hook.run(FsSyncShutdow
nHook.java:93)
Caused by: java.lang.ClassNotFoundException: de.schlichtherle.truezip.fs.FsLockC
ontroller$1Sync
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(
SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadCl
ass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm
.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm
.java:239)
        ... 7 more

- Maven 3.5
- alfresco-platform-jar-archetype version 3.0.0-beta-5. Also not working on 3.0.0 

NEED HELP, PLEASE
